name: Update images workflow

concurrency: automatic_pull_requests

on:
  repository_dispatch:
    types: dispatch-image

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Update image
        uses: prefapp/action-state-repo-update-image@feature/v3
        with:
          tenant: ${{ github.event.client_payload.tenant }}
          application: ${{ github.event.client_payload.app }}
          environment: ${{ github.event.client_payload.env }}
          service_names: ${{ toJSON(github.event.client_payload.service_names) }}
          image: ${{ github.event.client_payload.image }}
          reviewers: ${{ toJSON(github.event.client_payload.reviewers) }}
          token: ${{ secrets.PAT_DEPLOY }}
