name: Dispatch workflow

on:
  repository_dispatch:
    types: test-dispatch-event

env:
  image_file: ''
  base_branch: 'main'
  repo_name: 'test-state'
  project_name: 'prefapp'
  repo_git_user: 'github-actions'
  repo_git_mail: 'github-actions@github.com'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Print payload
        id: branch
        run: |
           echo ${{ github.event.client_payload.actor }} 
           echo ${{ github.event.client_payload.image }} 
           echo ${{ github.event.client_payload.environment }} 
           echo ${{ github.event.client_payload.service }} 
           
      - name: Create branch with changes
        run: |
          git config --global user.name ${{ env.repo_git_user }}
          git config --global user.email ${{ env.repo_git_mail }}
          git checkout -b newbranch
          touch test.txt
          git add test.txt
          git commit -m "commit msg"
          git push origin newbranch
      - name: Create Pull Request
        run: |
          git config --global user.name ${{ env.repo_git_user }}
          git config --global user.email ${{ env.repo_git_mail }}
          ls -l
          echo ${GITHUB_TOKEN}
          docker run -v $(pwd):/repo prefapp/prefapp-cicdpy:cd github.pr_auto_merge \
             token=${{ secrets.GITHUB_TOKEN }} \
             titulo="tituloPR" \
             rama_origen=newbranch \
             repo=${{ env.repo_name }} \
             proyecto=${{ env.project_name }} \
             reviewers='${{ github.event.client_payload.actor }}'
