name: Update images workflow

concurrency: automatic_pull_requests

on:
  repository_dispatch:
    types: dispatch-image

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Update image
        id: gh
        uses: prefapp/action-state-repo-update-image@fix/error-handling
        with:
          input_matrix: ${{ toJSON(github.event.client_payload) }}
