name: Update image

on:
  repository_dispatch:
    types: test-dispatch-imagen

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        
      - name: Print all
        run: |
          echo ${{ toJSON(github.event.client_payload) }}
      - uses: actions/checkout@v2  #NECESSARY
      
      - name: Update image
        uses: prefapp/action-state-repo-update-image@v4
        with:
          input_matrix: ${{ toJSON(github.event.client_payload) }}
