name: Update image

on:
  repository_dispatch:
    types: [test-dispatch-image]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update image
        uses: prefapp/action-state-repo-update-image@fix/single-pr-for-multiple-tenant-app-env-changes
        with:
          input_matrix: ${{ toJSON(github.event.client_payload) }}
          token: ${{ secrets.REPO_STATE_PR_TOKEN }}
